### ISSUE TITLE
Definition In Header File

### ISSUE THREAD

**Issue by aeoranday** [DUNE-DAQ/hdf5libs#105]
https://github.com/DUNE-DAQ/hdf5libs/blob/1012821c0aef85cffe88ff4a8739bac354b5aea9/include/hdf5libs/HDF5RawDataFile.hpp#L509-L512

The above definition appears in a header file and results in the `multiple definitions` compilation error when multiple translation units include this file. It seems like this file should be cleaned into a detailed `*.hxx` and moving this definition into the `*.cpp`.

**Comment by eflumerf** [comment]
Or mark the method `inline`

**Comment by aeoranday** [comment]
Since it hasn't been a problem so far (AFAIK), `inline` may be sufficient. However, I think it would be best to move out of the header file.

**Comment by bieryAtFnal** [comment]
It seems very reasonable to me to move this method to the source file.

Probably it ended up in the header  file as an oversight when the many templated get_attribute methods were implemented.

The move is available in PR #108 .
