### ISSUE TITLE
Move hdf5dump and friends from dfmodules to hdf5libs

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/hdf5libs#21]
Move the data dump utilities that only depend on daqdataformats to hdf5libs.

A next step would be to overhaul them a bit to make use of the hdf5libs-given utilities.

**Comment by wesketchum** [comment]
(This includes merging in Pengfei's updates to the hdf5_dump to handle TimeSlices, so that the utility also works on timeslice data.)

**Comment by bieryAtFnal** [comment]
Not sure why this Issue didn't get closed automatically when the linked PR was merged, but I'm closing it now.
