### ISSUE TITLE
Work on integration with rawdatautils and decoder utilities

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/hdf5libs#24]
This was mentioned at the 23-Mar DFWG meeting, and I wanted to create a placeholder for it.
Additional details welcome...

**Comment by bieryAtFnal** [comment]
My understanding is that this Issue is for tasks that have somewhat of an ongoing-work nature, and I believe that there are no changes for v2.11.0, so I'm re-assigning it to v3.0.0.

**Comment by roland-sipos** [comment]
To my understanding, this can be closed with the merged PR?

**Comment by bieryAtFnal** [comment]
Yes, let's do that.
