### ISSUE TITLE
Missing methods in the python binding of HDF5RawDataFile

### ISSUE THREAD

**Issue by adam-abed-abud** [DUNE-DAQ/hdf5libs#42]
The `HDF5RawDataFile` as it is currently is missing some methods, for example "get_geo_ids_for_subdetector". As a consequence, the python script `wib2decoder.py` does not work and it raises the issue: 
```
AttributeError: 'HDF5RawDataFile' object has no attribute 'get_geo_ids_for_subdetector'
```
How to fix:  add in `hdf5libs/python/hdf5libs/__init__.py` the following lines: 
```
    def get_geo_ids_for_subdetector(self,*args,**kwargs):
        return sorted(super().get_geo_ids_for_subdetector(*args,**kwargs))
```

**Comment by bieryAtFnal** [comment]
wib2decoder.py *does* work with develop branches 
AND
get_geo_ids_for_subdetector *does* exist in the hdf5libs python bindings, as shown here:
[https://github.com/DUNE-DAQ/hdf5libs/blob/dfd3feb7fe103e8963fc5783c57ffbc59606d684/pybindsrc/hdf5rawdatafile.cpp#L134
](https://github.com/DUNE-DAQ/hdf5libs/blob/dfd3feb7fe103e8963fc5783c57ffbc59606d684/pybindsrc/hdf5rawdatafile.cpp#L134
)

Adam, maybe you need to merge develop branches into your feature branches?
