### ISSUE TITLE
Code deeply of out compliance with style guide

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/hdf5libs#5]
I just ran `dbt-build.py --lint` on the `develop` branch of hdf5libs and there are many, many linting errors. This also suggests there may be other deviations from the style guide which aren't lintable. An effort should be made to clean up the code and bring it reasonably in line with the standards set in https://dune-daq-sw.readthedocs.io/en/latest/packages/styleguide/ .

**Comment by jcfreeman2** [comment]
I should add that since some code will be removed outright, obviously code which will be retained should be given more attention.

**Comment by wesketchum** [comment]
Thanks to John and Eric, the state of the code is much better and passes linting in the `restructuring_hdf5libs` branch. There may still be some style guide improvements to be done, but I think when we merge in the restructuring branch we can close the issue for being "deeply" out of compliance.

**Comment by jcfreeman2** [comment]
Agreed.
